CONFIG_ZMK_KEYBOARD_NAME="Sweep"

# enable deep sleep support
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# fix connection issues with latest linux kernel https://github.com/zmkfirmware/zmk/issues/1487.
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# enable peripheral battery status
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
